//! Code generator for semantic validation dispatchers.
//!
//! Reads [`SemanticRule`] definitions and generates a Rust dispatcher
//! that calls hand-implemented check functions based on element type.

use crate::hierarchy_generator::TypeHierarchy;
use crate::semantic_rule_parser::{group_rules_by_element_type, SemanticRule};

/// Generate the semantic validation dispatcher with an optional type hierarchy.
///
/// The generated code contains:
/// - `validate_semantic(graph: &ModelGraph) -> Vec<SemanticError>` entry point
/// - Per-element-type dispatch functions
///
/// Each dispatch function calls into hand-implemented check functions
/// defined in `sysml_core::semantic_checks::*`.
///
/// If `hierarchy` is provided, base types are derived from the type hierarchy
/// (types that have subtypes). Otherwise falls back to a static list.
///
/// When a hierarchy is provided, `is_base_type` is derived from it dynamically
/// (any type that has subtypes in the hierarchy is considered a base type).
pub fn generate_semantic_validation_with_hierarchy(
    rules: &[SemanticRule],
    hierarchy: Option<&TypeHierarchy>,
) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated semantic validation dispatcher.\n");
    output.push_str("// DO NOT EDIT - generated by semantic_validation_generator.rs\n");
    output.push_str("//\n");
    output.push_str(&format!(
        "// {} rules from semantic_rules.toml\n\n",
        rules.len()
    ));

    // Generate the main entry point
    generate_entry_point(&mut output, rules, hierarchy);

    output
}

/// Generate the `validate_semantic` entry function.
#[allow(clippy::indexing_slicing)] // Bounds: iterating over grouped keys ensures valid access
fn generate_entry_point(
    output: &mut String,
    rules: &[SemanticRule],
    hierarchy: Option<&TypeHierarchy>,
) {
    let grouped = group_rules_by_element_type(rules);

    // Collect all element types that have rules
    let mut element_types: Vec<&String> = grouped.keys().collect();
    element_types.sort();

    output.push_str("/// Validate all semantic constraints on a model graph.\n");
    output.push_str("///\n");
    output.push_str("/// Returns a list of semantic errors found in the model.\n");
    output.push_str("/// This is generated from the semantic_rules.toml catalog.\n");
    output.push_str("pub fn validate_semantic(graph: &ModelGraph) -> Vec<SemanticError> {\n");
    output.push_str("    let mut errors = Vec::new();\n\n");
    output.push_str("    for element in graph.elements.values() {\n");
    output.push_str("        match element.kind {\n");

    for element_type in &element_types {
        let type_rules = &grouped[*element_type];

        output.push_str(&format!(
            "            ElementKind::{} => {{\n",
            element_type
        ));

        // Rule inheritance: a rule registered on a SUPERTYPE also applies to this
        // (concrete) subtype — e.g. at-most-one-objective registered on
        // CaseDefinition must fire on UseCaseDefinition. A `match` arm is
        // exclusive, so a subtype with its own arm never reaches the `_ =>`
        // subtype catch-all below; emit its transitive-supertype rules here.
        // Deduped by (category, check) so a check is invoked at most once per
        // element (no duplicate diagnostics). Requires the hierarchy; without it
        // (legacy) only the type's own rules are emitted.
        let mut emitted: std::collections::HashSet<(String, String)> =
            std::collections::HashSet::new();
        if let Some(h) = hierarchy {
            if let Some(supertypes) = h.get_supertypes(element_type) {
                for ancestor in supertypes {
                    if let Some(ancestor_rules) = grouped.get(ancestor) {
                        for rule in ancestor_rules {
                            if emitted.insert((rule.category.clone(), rule.check.clone())) {
                                generate_rule_call(output, rule);
                            }
                        }
                    }
                }
            }
        }

        for rule in type_rules {
            if emitted.insert((rule.category.clone(), rule.check.clone())) {
                generate_rule_call(output, rule);
            }
        }

        output.push_str("            }\n");
    }

    output.push_str("            _ => {\n");

    // For base types, check if the element is a subtype
    let base_types: Vec<&&String> = element_types
        .iter()
        .filter(|t| is_base_type(t, hierarchy))
        .collect();

    if !base_types.is_empty() {
        output.push_str("                // Check base type rules for subtypes\n");
        for base_type in &base_types {
            let type_rules = &grouped[**base_type];
            output.push_str(&format!(
                "                if element.kind.is_subtype_of(ElementKind::{}) {{\n",
                base_type
            ));
            for rule in type_rules {
                generate_rule_call_indented(output, rule, "                    ");
            }
            output.push_str("                }\n");
        }
    }

    output.push_str("            }\n");
    output.push_str("        }\n");
    output.push_str("    }\n\n");
    output.push_str("    errors\n");
    output.push_str("}\n");
}

/// Static list of base types for backward compatibility when no hierarchy is provided.
const STATIC_BASE_TYPES: &[&str] = &[
    "Namespace",
    "Type",
    "Feature",
    "Usage",
    "Definition",
    "Classifier",
    "Class",
    "DataType",
    "Structure",
    "Behavior",
];

/// Check if an element type is a base type that subtypes should also match.
///
/// When a hierarchy is provided, a type is considered a "base type" if it has
/// subtypes in the hierarchy. Otherwise falls back to a static list of known
/// base types.
fn is_base_type(element_type: &str, hierarchy: Option<&TypeHierarchy>) -> bool {
    match hierarchy {
        Some(h) => h.has_subtypes(element_type),
        None => STATIC_BASE_TYPES.contains(&element_type),
    }
}

/// Generate a single rule check call.
fn generate_rule_call(output: &mut String, rule: &SemanticRule) {
    generate_rule_call_indented(output, rule, "                ");
}

/// Generate a single rule check call with custom indentation.
fn generate_rule_call_indented(output: &mut String, rule: &SemanticRule, indent: &str) {
    let check_module = category_to_module(&rule.category);

    output.push_str(&format!("{}// {} - {}\n", indent, rule.id, rule.message));
    output.push_str(&format!(
        "{}if let Some(e) = semantic_checks::{}::{}(element, graph) {{\n",
        indent, check_module, rule.check
    ));
    output.push_str(&format!("{}    errors.extend(e);\n", indent));
    output.push_str(&format!("{}}}\n", indent));
}

/// Map a rule category to its check module name.
fn category_to_module(category: &str) -> &str {
    match category {
        "distinguishability" => "distinguishability",
        "typing" => "typing",
        "ownership" => "ownership",
        "cardinality" => "cardinality",
        "specialization" => "specialization",
        "variation" => "variation",
        "connector" => "connectors",
        "port" => "ports",
        "state" => "states",
        "action" => "actions",
        "requirement" => "requirements",
        "expression" => "expressions",
        _ => "custom",
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::indexing_slicing)]
mod tests {
    use super::*;
    use crate::semantic_rule_parser::parse_semantic_rules;

    #[test]
    fn generates_dispatcher() {
        let toml = r#"
[[rule]]
id = "S001"
element_type = "Namespace"
category = "distinguishability"
severity = "warning"
message = "Duplicate member name"
check = "unique_owned_member_names"
spec_ref = "KerML 7.2.3"

[[rule]]
id = "S010"
element_type = "Usage"
category = "typing"
severity = "error"
message = "Must be typed by definitions"
check = "usage_typed_by_definitions"
spec_ref = "SysML 8.2.4"
"#;
        let rules = parse_semantic_rules(toml).unwrap();
        let code = generate_semantic_validation_with_hierarchy(&rules, None);

        assert!(code.contains("pub fn validate_semantic"));
        assert!(code.contains("ElementKind::Namespace"));
        assert!(code.contains("semantic_checks::distinguishability::unique_owned_member_names"));
        assert!(code.contains("semantic_checks::typing::usage_typed_by_definitions"));
        // Usage is a base type, so it should also appear in the subtype fallback
        assert!(code.contains("is_subtype_of(ElementKind::Usage)"));
    }

    #[test]
    fn category_module_mapping() {
        assert_eq!(
            category_to_module("distinguishability"),
            "distinguishability"
        );
        assert_eq!(category_to_module("typing"), "typing");
        assert_eq!(category_to_module("ownership"), "ownership");
        assert_eq!(category_to_module("specialization"), "specialization");
        assert_eq!(category_to_module("variation"), "variation");
    }

    #[test]
    fn subtype_arm_inherits_supertype_rules() {
        use crate::ttl_parser::TypeInfo;

        fn make_type(name: &str, supertypes: &[&str]) -> TypeInfo {
            TypeInfo {
                name: name.to_string(),
                supertypes: supertypes.iter().map(|s| s.to_string()).collect(),
                comment: None,
            }
        }

        // CaseDefinition carries at-most-one-objective; UseCaseDefinition is a
        // SUBTYPE that also has its OWN rule (so it gets an explicit match arm,
        // NOT the `_ =>` catch-all). The subtype's arm must INHERIT the
        // CaseDefinition rule — this guards the rule-inheritance dispatch so a
        // future case subtype can never silently miss inherited rules.
        let toml = r#"
[[rule]]
id = "S064"
element_type = "CaseDefinition"
category = "cardinality"
severity = "error"
message = "A case definition can have at most one objective"
check = "at_most_one_objective"
spec_ref = "SysML 8.3.22.2"

[[rule]]
id = "S139"
element_type = "UseCaseDefinition"
category = "requirements"
severity = "error"
message = "A use case can have at most one subject"
check = "use_case_at_most_one_subject"
spec_ref = "SysML 8.3"
"#;
        let rules = parse_semantic_rules(toml).unwrap();
        let kerml = vec![make_type("Element", &[]), make_type("Definition", &["Element"])];
        let sysml = vec![
            make_type("CaseDefinition", &["Definition"]),
            make_type("UseCaseDefinition", &["CaseDefinition"]),
        ];
        let hierarchy = TypeHierarchy::new(&kerml, &sysml);
        let code = generate_semantic_validation_with_hierarchy(&rules, Some(&hierarchy));

        // Isolate the UseCaseDefinition match arm (up to the next arm).
        let start = code
            .find("ElementKind::UseCaseDefinition =>")
            .expect("UseCaseDefinition arm generated");
        let end = code[start + 1..]
            .find("\n            ElementKind::")
            .map_or(code.len(), |e| start + 1 + e);
        let arm = &code[start..end];
        assert!(
            arm.contains("at_most_one_objective"),
            "UseCaseDefinition arm must INHERIT CaseDefinition's at_most_one_objective rule; arm:\n{arm}"
        );
        assert!(
            arm.contains("use_case_at_most_one_subject"),
            "UseCaseDefinition arm must keep its own rule too; arm:\n{arm}"
        );
    }

    #[test]
    fn hierarchy_derived_base_types_cover_static_list() {
        use crate::ttl_parser::TypeInfo;

        fn make_type(name: &str, supertypes: &[&str]) -> TypeInfo {
            TypeInfo {
                name: name.to_string(),
                supertypes: supertypes.iter().map(|s| s.to_string()).collect(),
                comment: None,
            }
        }

        // Build a realistic hierarchy that includes all 10 static base types
        // and their subtypes
        let kerml = vec![
            make_type("Element", &[]),
            make_type("Namespace", &["Element"]),
            make_type("Type", &["Namespace"]),
            make_type("Feature", &["Type"]),
            make_type("Classifier", &["Type"]),
            make_type("Class", &["Classifier"]),
            make_type("DataType", &["Classifier"]),
            make_type("Structure", &["Class"]),
            make_type("Behavior", &["Class"]),
        ];
        let sysml = vec![
            make_type("Definition", &["Classifier"]),
            make_type("Usage", &["Feature"]),
            make_type("PartDefinition", &["Definition"]),
            make_type("PartUsage", &["Usage"]),
            make_type("Package", &["Namespace"]),
            make_type("SubFeature", &["Feature"]),
            make_type("SubClass", &["Class"]),
            make_type("SubDataType", &["DataType"]),
            make_type("SubStructure", &["Structure"]),
            make_type("SubBehavior", &["Behavior"]),
        ];

        let hierarchy = TypeHierarchy::new(&kerml, &sysml);

        // All 10 original static base types should be identified as having subtypes
        for base_type in STATIC_BASE_TYPES {
            assert!(
                hierarchy.has_subtypes(base_type),
                "{} should be identified as having subtypes in the hierarchy",
                base_type
            );
        }
    }

    #[test]
    fn hierarchy_based_dispatch_generates_same_structure() {
        use crate::ttl_parser::TypeInfo;

        fn make_type(name: &str, supertypes: &[&str]) -> TypeInfo {
            TypeInfo {
                name: name.to_string(),
                supertypes: supertypes.iter().map(|s| s.to_string()).collect(),
                comment: None,
            }
        }

        let kerml = vec![
            make_type("Element", &[]),
            make_type("Namespace", &["Element"]),
            make_type("Type", &["Namespace"]),
            make_type("Feature", &["Type"]),
            make_type("Package", &["Namespace"]),
        ];
        let sysml = vec![
            make_type("Usage", &["Feature"]),
            make_type("PartUsage", &["Usage"]),
        ];

        let hierarchy = TypeHierarchy::new(&kerml, &sysml);

        let toml = r#"
[[rule]]
id = "S001"
element_type = "Namespace"
category = "distinguishability"
severity = "warning"
message = "Duplicate member name"
check = "unique_owned_member_names"
spec_ref = "KerML 7.2.3"

[[rule]]
id = "S010"
element_type = "Usage"
category = "typing"
severity = "error"
message = "Must be typed by definitions"
check = "usage_typed_by_definitions"
spec_ref = "SysML 8.2.4"
"#;
        let rules = parse_semantic_rules(toml).unwrap();
        let code = generate_semantic_validation_with_hierarchy(&rules, Some(&hierarchy));

        // Namespace has subtypes (Type, Feature, Package, Usage, PartUsage) so it should be a base type
        assert!(
            code.contains("is_subtype_of(ElementKind::Namespace)"),
            "Namespace should get subtype dispatch with hierarchy"
        );
        // Usage has subtypes (PartUsage) so it should also be a base type
        assert!(
            code.contains("is_subtype_of(ElementKind::Usage)"),
            "Usage should get subtype dispatch with hierarchy"
        );
    }
}
