#!/bin/bash
# Generate tree-sitter keywords/operators/enums from xtext specifications
# Usage: ./generate_from_xtext.sh [--inline]
#
# Without --inline: generates separate JS files in generated/
# With --inline: prints inline JS for copy-paste into grammar.js

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Default to the in-repo reference spec (tree-sitter/ is four levels below the
# workspace root: tree-sitter → sysml-parser-incremental → lang → crates → root).
# Override with SYSML_REFS_DIR to point at an out-of-tree spec checkout.
REFS_DIR="${SYSML_REFS_DIR:-$SCRIPT_DIR/../../../../references/sysmlv2}"
OUTPUT_DIR="${SYSML_TS_OUTPUT_DIR:-$SCRIPT_DIR/generated}"

SYSML_XTEXT="$REFS_DIR/SysML-v2-Pilot-Implementation/org.omg.sysml.xtext/src/org/omg/sysml/xtext/SysML.xtext"
KERML_XTEXT="$REFS_DIR/SysML-v2-Pilot-Implementation/org.omg.kerml.xtext/src/org/omg/kerml/xtext/KerML.xtext"
KERML_EXPR_XTEXT="$REFS_DIR/SysML-v2-Pilot-Implementation/org.omg.kerml.expressions.xtext/src/org/omg/kerml/expressions/xtext/KerMLExpressions.xtext"

INLINE_MODE=false
if [[ "$1" == "--inline" ]]; then
    INLINE_MODE=true
fi

# Extract keywords (quoted alphabetic strings from xtext, min 2 chars)
extract_keywords() {
    grep -ohP "'[a-z]{2,}'" "$SYSML_XTEXT" "$KERML_XTEXT" "$KERML_EXPR_XTEXT" 2>/dev/null | \
        tr -d "'" | sort -u
}

# Format keywords as JS array (8 per line for readability)
format_keywords_inline() {
    local keywords="$1"
    echo "// Inlined from generated/keywords.js"
    echo "const keywords = ["
    echo "$keywords" | paste -sd',' | sed 's/,/", "/g' | sed 's/^/"/' | sed 's/$/"/' | \
        fold -s -w 76 | sed 's/^/  /' | sed 's/$/,/'
    echo "];"
}

# Generate keywords.js module
generate_keywords_module() {
    local keywords="$1"
    cat << 'HEADER'
/**
 * AUTO-GENERATED from SysML v2 xtext specification.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated by: generate_from_xtext.sh
 * Source: SysML.xtext, KerML.xtext, KerMLExpressions.xtext
 */
module.exports = [
HEADER
    echo "$keywords" | while read KW; do
        [ -n "$KW" ] && echo "  \"$KW\","
    done
    echo "];"
}

# Operators (hardcoded from KerMLExpressions.xtext structure)
OPERATORS='// Inlined from generated/operators.js
const operators = [
  { name: "ConditionalOperator", category: "conditional", precedence: 1, symbols: ["if"] },
  { name: "NullCoalescingOperator", category: "null_coalescing", precedence: 2, symbols: ["??"] },
  { name: "ImpliesOperator", category: "implies", precedence: 3, symbols: ["implies"] },
  { name: "OrOperator", category: "or", precedence: 4, symbols: ["|"] },
  { name: "ConditionalOrOperator", category: "conditional_or", precedence: 4, symbols: ["or"] },
  { name: "XorOperator", category: "xor", precedence: 5, symbols: ["xor"] },
  { name: "AndOperator", category: "and", precedence: 6, symbols: ["&"] },
  { name: "ConditionalAndOperator", category: "conditional_and", precedence: 6, symbols: ["and"] },
  { name: "EqualityOperator", category: "equality", precedence: 7, symbols: ["===", "!==", "==", "!="] },
  { name: "ClassificationTestOperator", category: "classification_test", precedence: 8, symbols: ["hastype", "istype", "@"] },
  { name: "MetaClassificationTestOperator", category: "meta_classification_test", precedence: 9, symbols: ["@@"] },
  { name: "CastOperator", category: "cast", precedence: 10, symbols: ["as"] },
  { name: "MetaCastOperator", category: "meta_cast", precedence: 10, symbols: ["meta"] },
  { name: "RelationalOperator", category: "relational", precedence: 11, symbols: ["<=", ">=", "<", ">"] },
  { name: "RangeOperator", category: "range", precedence: 12, symbols: [".."] },
  { name: "AdditiveOperator", category: "additive", precedence: 13, symbols: ["+", "-"] },
  { name: "MultiplicativeOperator", category: "multiplicative", precedence: 14, symbols: ["*", "/", "%"] },
  { name: "ExponentiationOperator", category: "exponentiation", precedence: 15, symbols: ["**", "^"] },
  { name: "UnaryOperator", category: "unary", precedence: 16, symbols: ["+", "-", "~", "not"] },
];'

# Enums (hardcoded from SysML.xtext enum rules)
ENUMS='// Inlined from generated/enums.js
const enums = {
  "FeatureDirectionKind": ["inout", "out", "in"],
  "PortionKind": ["timeslice", "snapshot"],
  "RequirementConstraintKind": ["require", "assume", "frame", "verify"],
  "StateSubactionKind": ["entry", "exit", "do"],
  "TransitionFeatureKind": ["trigger", "guard", "effect"],
  "TriggerKind": ["after", "when", "at"],
  "VisibilityKind": ["protected", "private", "public", "expose"],
};'

# Extract keywords
KEYWORDS=$(extract_keywords)
KEYWORD_COUNT=$(echo "$KEYWORDS" | wc -l)

if $INLINE_MODE; then
    echo "=== Copy the following into grammar.js (after the header comment) ==="
    echo ""

    # Keywords as inline array
    echo "// Inlined from generated/keywords.js"
    echo "const keywords = ["

    # Format 8 keywords per line
    echo "$KEYWORDS" | awk '
    BEGIN { line = "" }
    {
        if (line == "") {
            line = "  \"" $0 "\""
        } else {
            line = line ", \"" $0 "\""
        }
        if (NR % 8 == 0) {
            print line ","
            line = ""
        }
    }
    END {
        if (line != "") {
            print line ","
        }
    }'

    echo "];"
    echo ""
    echo "$OPERATORS"
    echo ""
    echo "$ENUMS"
    echo ""
    echo "=== End of inline content ==="
else
    mkdir -p "$OUTPUT_DIR"

    echo "=== Generating Tree-sitter Constants from Xtext ==="
    echo "Output: $OUTPUT_DIR"

    # Generate keywords.js
    generate_keywords_module "$KEYWORDS" > "$OUTPUT_DIR/keywords.js"

    # Generate operators.js
    cat > "$OUTPUT_DIR/operators.js" << 'HEADER'
/**
 * AUTO-GENERATED from SysML v2 xtext specification.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated by: generate_from_xtext.sh
 * Source: KerMLExpressions.xtext
 */
HEADER
    # `${OPERATORS#*$'\n'}` already strips the leading `// Inlined ...` comment,
    # leaving `const operators = [ ... ];` — rewrite that opening line to
    # `module.exports = [`. (A stray `tail -n +2` here used to drop the opening
    # line entirely, producing a file with no `module.exports`.)
    echo "${OPERATORS#*$'\n'}" | sed 's/^const operators = /module.exports = /' >> "$OUTPUT_DIR/operators.js"

    # Generate enums.js
    cat > "$OUTPUT_DIR/enums.js" << 'HEADER'
/**
 * AUTO-GENERATED from SysML v2 xtext specification.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated by: generate_from_xtext.sh
 * Source: SysML.xtext
 */
HEADER
    # Same fix as operators.js: strip only the comment line, then rewrite the
    # `const enums = {` opening to `module.exports = {`.
    echo "${ENUMS#*$'\n'}" | sed 's/^const enums = /module.exports = /' >> "$OUTPUT_DIR/enums.js"

    echo ""
    echo "=== Generated Files ==="
    ls -la "$OUTPUT_DIR"
    echo ""
    echo "Keywords: $KEYWORD_COUNT"
    echo "Operators: 19"
    echo "Enums: 7"
    echo ""
    echo "To update grammar.js, run: ./generate_from_xtext.sh --inline"
fi
