#!/usr/bin/env python3
"""Deterministic generator for the espresso-production-cell demand/ambient
profiles (DATA-03). Analytic, seedless, byte-stable, self-checking.

It emits two CSV files under ``data/`` and rewrites ``fixture-provenance.toml``
with matching sha256/row_count entries, so
``cargo test -p sysml-spec-tests --test fixture_provenance`` stays green and a
clean-checkout re-run reproduces the committed bytes exactly.

Design (independently derived — no product data):

  demand(t)  = D0 + sum_k A_k * pulse(t; c_k, w_k)          [litres/min, aggregate]
      pulse(t;c,w) = smoothstep((t-(c-w))/w) - smoothstep((t-c)/w)
      a bounded, C1, non-negative bump centred at c of half-width w. Two bumps
      (a morning and an afternoon service peak) with fixed phase offsets model
      the aggregate station draw over a service window.

  ambient(t) = T0 + Ta * sin(2*pi*t / P)                    [deg C, room air]
      a single low-frequency diurnal sinusoid.

Sample grid: t = 0, DT, 2*DT, ... , T_END inclusive (both endpoints emitted).

Run:  python3 scripts/generate_profiles.py      (from the fixture directory)
"""

import hashlib
import math
import os

# ---- fixture identity (kept in sync with the [fixture] block) --------------
FIXTURE_NAME = "espresso-production-cell"
FIXTURE_VERSION = "1.0.0"
FIXTURE_CREATED = "2026-08-02"

# ---- sampling grid ---------------------------------------------------------
T_END = 120.0          # seconds
DT = 1.0               # sample interval (seconds)
DECIMALS = 6           # fixed fractional digits (byte-stable formatting)

# ---- demand model ----------------------------------------------------------
D0 = 1.0               # baseline aggregate draw (l/min)
PULSES = [             # (centre c, half-width w, amplitude A)
    (35.0, 15.0, 3.0),
    (85.0, 20.0, 2.0),
]

# ---- ambient model ---------------------------------------------------------
T0 = 22.0              # mean room temperature (deg C)
TA = 3.0              # amplitude (deg C)
P = 240.0             # period (seconds)


def smoothstep(x):
    """C1 smoothstep clamped to [0,1]."""
    if x <= 0.0:
        return 0.0
    if x >= 1.0:
        return 1.0
    return x * x * (3.0 - 2.0 * x)


def pulse(t, c, w):
    """A bounded C1 bump on [c-w, c] with unit height."""
    return smoothstep((t - (c - w)) / w) - smoothstep((t - c) / w)


def demand(t):
    v = D0
    for (c, w, a) in PULSES:
        v += a * pulse(t, c, w)
    return v


def ambient(t):
    return T0 + TA * math.sin(2.0 * math.pi * t / P)


def grid():
    n = int(round(T_END / DT)) + 1
    return [i * DT for i in range(n)]


def fmt(x):
    return f"{x:.{DECIMALS}f}"


def build_csv(header, fn):
    lines = [header]
    for t in grid():
        lines.append(f"{fmt(t)},{fmt(fn(t))}")
    return "\n".join(lines) + "\n"


def self_check(fn, lo, hi, name):
    ts = grid()
    vals = [fn(t) for t in ts]
    assert all(math.isfinite(v) for v in vals), f"{name}: non-finite value"
    assert all(lo <= v <= hi for v in vals), f"{name}: out of [{lo},{hi}]"
    # endpoints are exactly on the grid
    assert abs(ts[0]) < 1e-12 and abs(ts[-1] - T_END) < 1e-12, f"{name}: grid endpoints"
    return len(vals)


def sha256_of(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


DATA_TEMPLATE = """\
[[data]]
path                  = "{path}"
origin                = "synthetic-equation"
generator             = "scripts/generate_profiles.py@{ver}"
generator_config      = "{cfg}"
equation_id           = "{eq}"
units                 = "{units}"
value_range           = "{vrange}"
row_count             = {rows}
sha256                = "{sha}"
regeneration_command  = "python3 scripts/generate_profiles.py"
"""


def manifest(entries):
    head = (
        "# Provenance manifest for the espresso-production-cell public fixture (DATA-01).\n"
        "# GENERATED by scripts/generate_profiles.py — do not hand-edit the [[data]] blocks.\n"
        "# Validated by `cargo test -p sysml-spec-tests --test fixture_provenance`.\n\n"
        "[fixture]\n"
        f'name          = "{FIXTURE_NAME}"\n'
        f'version       = "{FIXTURE_VERSION}"\n'
        f'created       = "{FIXTURE_CREATED}"\n'
        'design_source = "capability-contract"\n\n'
    )
    return head + "\n".join(entries)


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_dir = os.path.join(here, "data")
    os.makedirs(data_dir, exist_ok=True)

    # self-check BEFORE writing (fail hard, never emit a partial file)
    d_rows = self_check(demand, 0.0, 10.0, "demand")
    a_rows = self_check(ambient, T0 - TA - 1e-9, T0 + TA + 1e-9, "ambient")

    demand_csv = build_csv("t,demand", demand)
    ambient_csv = build_csv("t,ambient", ambient)

    with open(os.path.join(data_dir, "generated_demand.csv"), "w", newline="\n") as f:
        f.write(demand_csv)
    with open(os.path.join(data_dir, "generated_ambient.csv"), "w", newline="\n") as f:
        f.write(ambient_csv)

    entries = [
        DATA_TEMPLATE.format(
            path="data/generated_demand.csv", ver=FIXTURE_VERSION,
            cfg=f"T_END={T_END}; DT={DT}; D0={D0}; pulses={PULSES}",
            eq="demand(t)=D0+sum A_k*(smoothstep((t-(c-w))/w)-smoothstep((t-c)/w))",
            units="t:seconds, demand:litres-per-minute",
            vrange="t in [0,120], demand in [1.0, ~6.0]",
            rows=d_rows, sha=sha256_of(demand_csv),
        ),
        DATA_TEMPLATE.format(
            path="data/generated_ambient.csv", ver=FIXTURE_VERSION,
            cfg=f"T_END={T_END}; DT={DT}; T0={T0}; TA={TA}; P={P}",
            eq="ambient(t)=T0+TA*sin(2*pi*t/P)",
            units="t:seconds, ambient:degC",
            vrange="t in [0,120], ambient in [19.0, 25.0]",
            rows=a_rows, sha=sha256_of(ambient_csv),
        ),
    ]
    with open(os.path.join(here, "fixture-provenance.toml"), "w", newline="\n") as f:
        f.write(manifest(entries))

    print(f"wrote {d_rows}-row demand + {a_rows}-row ambient profiles and manifest")


if __name__ == "__main__":
    main()
